# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: commit changes
        run: |
          echo test >> testfile.txt
          git config user.email "you@example.com"
          git config user.name "Your Name"
          # For example, to stage all changes and commit
          git add -A
          git commit -m "Your commit message"
          # To push the changes to the remote repository
          git config --global credential.helper '!f() { sleep 1; echo "username=SwordAndFist token=${{secrets.MYTOKEN}}"; }; f'
          # git remote set-url origin https://SwordAndFist:${{secrets.MYTOKEN}}@github.com/SwordAndFist/References.git
          git push
          
